version: 2
sources:
  - name: raw
    database: real-time-stock-analytics-25     # project_id
    schema: stock                               # dataset
    tables:
      - name: bronze_stock_quotes_raw
